name: Security Scanning
on: pull_request

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Cache Gradle
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run tests
        run: ./gradlew test --no-daemon


        # Disabled for now to avoid slowing PR builds.
        # Intended to run on the main branch or as a nightly security scan.
        #- name: Dependency vulnerability scan
        #  run: ./gradlew dependencyCheckAnalyze
